- Membership/Views/Shared/_CookieConsentPartial.cshtml
This resolves the cookie banner not staying dismissed. See #3 for details!
> Fix for #3

- Membership/Startup.cs
Uses https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/
> Workaround Same-site cookie issue

- Membership/Views/Profile/Index.cshtml
- Membership/wwwroot/css/style.css
Final results should be something as follows.
Only when user clicks on the "Edit Profile" button, it shows the fields to edit.
The UI issue on footer is also corrected, as showed below.
> Introduced a better view for Profile instead of showing textboxes.

- Membership/Views/Home/Index.cshtml
I'm not able to run the site locally, and have therefore not previewed the site after the text was added. I tested directly in the browser.
Tried to keep the text fairly short, and hopefully easy to read.
Feedback appreciated!
> #25 Added member benefits information

- Membership/Views/Shared/_Layout.cshtml
- Membership/wwwroot/css/style.css
> fix horizontal scroll

- Membership/Views/Shared/_Layout.cshtml
- Membership/wwwroot/css/style.css
> sync css & js

- Membership/Views/Shared/Error.cshtml
> add layout to error page

- Membership/Views/Shared/_Layout.cshtml
issue https://github.com/dotnet-foundation/membership/issues/59
> sync navigation

- Membership/Views/Shared/_Layout.cshtml
https://github.com/dotnet-foundation/membership/issues/64
> add social icons

- Membership/wwwroot/css/style.css
fix issue https://github.com/dotnet-foundation/membership/issues/69
> update dropdown bg

- Membership/wwwroot/css/style.css
fix issue https://github.com/dotnet-foundation/membership/issues/75
> update submit buttons

- Membership/Views/Shared/_Layout.cshtml
https://github.com/dotnet-foundation/membership/issues/117
> add lang tag to html

- Membership/Views/Shared/_Layout.cshtml
https://github.com/dotnet-foundation/membership/issues/119
> Accessibility add alt to logos

- Membership/Views/Profile/PayDues.cshtml
fix issue https://github.com/dotnet-foundation/membership/issues/125
> add card indent on mobile

- Membership/Views/Profile/PayDues.cshtml
https://github.com/dotnet-foundation/membership/issues/138
> Accessibility - add alt to img

- Membership/Views/Shared/_Layout.cshtml
https://github.com/dotnet-foundation/membership/issues/140
> add member policy to menu

- Membership/Views/Shared/_Layout.cshtml
https://github.com/dotnet-foundation/membership/issues/144
> replace footer layout (sync main site)

- Membership/Views/Shared/_CookieConsentPartial.cshtml
https://github.com/dotnet-foundation/membership/issues/146
> fix link privacy-policy

- Membership/Views/Shared/_Layout.cshtml
resolve https://github.com/dotnet-foundation/membership/issues/171
> remove store link

- Membership/Views/Shared/_Layout.cshtml
resolve https://github.com/dotnet-foundation/membership/issues/173
> remove Academy links
